### PR TITLE
bump up 0.2.0

### PR DESCRIPTION
**Pull request by giwa**

### CODE REVIEW

**Comment by abetomo** [comment]
https://rubygems.org/gems/embulk-output-kintone/versions

Could you also update RubyGems?

**Comment by abetomo** [comment]
@giwa 
https://rubygems.org/gems/embulk-output-kintone/versions
Could you also update RubyGems?

**Comment by giwa** [comment]
@abetomo DONE!

**Comment by abetomo** [comment]
Thank you!

**Pull request merged**
